/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Canonical activity record — one per gateway/SDK/connector LLM call. Single source of truth shared by every producer (gateway, SDK) and consumer (collector, workers, ClickHouse). Field names track the OpenTelemetry GenAI semantic conventions (gen_ai.*). SECURITY: additionalProperties is false by design so raw prompt/completion content can never enter the analytics pipeline (CLAUDE.md rule 2) — the schema has no content field and rejects unknown ones. Versioned: never change without a major bump and cross-team review (CLAUDE.md).
 */
export interface AgentLedgerLlmCallEvent {
  /**
   * Event discriminator. Absent (gateway) or 'llm_call' both validate against this schema.
   */
  kind?: "llm_call";
  call_id: string;
  ts: string;
  tenant_id: string;
  team_id?: string;
  user_id?: string;
  app_id?: string;
  environment?: string;
  virtual_key_id?: string;
  agent_id?: string;
  run_id?: string;
  step_id?: string;
  provider?: string;
  request_model?: string;
  response_model?: string;
  operation_name?: string;
  input_tokens?: number;
  output_tokens?: number;
  cache_read_tokens?: number;
  cache_write_tokens?: number;
  cost_usd?: number;
  latency_ms?: number;
  status_code?: number;
  /**
   * Call outcome. blocked_* are gateway policy rejections. 'blocked_tool' (additive enum, ADR-032) is an inline tool/MCP-governance rejection — existing producers/consumers are unaffected and the ClickHouse status column is LowCardinality(String) with the blocked% rollup already matching it, so no migration is required.
   */
  status?:
    | "ok"
    | "upstream_error"
    | "blocked_dlp"
    | "blocked_budget"
    | "blocked_rate"
    | "blocked_policy"
    | "blocked_tool";
  prompt_hash?: string;
  dlp_action?: "allow" | "log" | "warn" | "redact" | "block";
  dlp_findings?: {
    class?: string;
    category?: string;
    severity?: "low" | "medium" | "high" | "critical";
    confidence?: number;
    count?: number;
  }[];
  risk_severity?: "" | "low" | "medium" | "high" | "critical";
  streamed?: boolean;
  /**
   * Ingestion provenance for cross-source dedup. 'adapter' = normalized from a 3rd-party gateway's spend/usage log (LiteLLM/Bifrost/Portkey); 'otel' = mapped from gen_ai.* OTLP spans. Additive enum (ADR-022): existing producers/consumers are unaffected; the ClickHouse source column is a plain LowCardinality(String), so no migration is required.
   */
  source?: "gateway" | "sdk" | "provider_export" | "adapter" | "otel";
}
